Feature/expenses chart by specific category
cabbageRolls/Kapusta pull request #13
Opened 2020-05-02 18:24 UTC by YEvhen-SHmatko

//<ExpensesChartBySpecificCategory
//   data={[
//     { name: 'chery', cost: '2500' },
//     { name: 'bacon', cost: '4500' },
//     { name: 'tomato', cost: '500' },
//     { name: 'chery', cost: '5500' },
//     { name: 'bacon', cost: '4100' },
//     { name: 'tomato', cost: '300' },
//     { name: 'chery', cost: '2000' },
//     { name: 'bacon', cost: '1500' },
//     { name: 'tomato', cost: '500' },
//     { name: 'tomato', cost: '200' },
//   ]}
// />

2020-05-02 21:03 UTC, tachka123 requested changes

2020-05-02 21:03 UTC, tachka123 commented on src/components/ExpensesChartBySpecificCategory/ExpensesChartBySpecificCategory.jsx
> +    .sort((a, b) => b.cost - a.cost)
'await JSON.parse(JSON.stringify(json))'

2020-05-02 21:03 UTC, tachka123 commented on src/components/ExpensesChartBySpecificCategory/ExpensesChartBySpecificCategory.jsx
> +    .sort((a, b) => b.cost - a.cost)
зачем await, зачем json.parse(json..stringify(json)??

2020-05-03 08:26 UTC, YEvhen-SHmatko commented
Методы JSON-a использую для решения проблем с мутабельностью. А async/await — это одна из самых полезных революционных возможностей, добавленных в JavaScript в последние несколько лет. Она даёт простые и удобные способы написания и отладки асинхронного кода. Вечером эти моменты уберу.

2020-05-03 12:22 UTC, tachka123 commented
Методы JSON-а не возвращают Promise

2020-05-04 14:36 UTC, YEvhen-SHmatko commented
Я этого не писал, видимо ты не смог правильно прочитать комментарий.

2020-05-04 16:22 UTC, tachka123 commented
Видимо ты не смог понять зачем нужен async/await

2020-05-04 16:31 UTC, tachka123 approved these changes
nice bike

2020-05-04 16:31 UTC, tachka123 commented on src/services/mediaQuery.js
>  };
интересный подход)

2020-05-04 16:31 UTC, merged